#include <ltsmin/pins.h>
const int rers_get_state_size();
int rers_get_type_count();
const char *rers_get_type_name(int type);
int rers_get_type_value_count(int type);
const char* rers_get_state_variable_name(unsigned int var);
int rers_get_state_variable_type(int var);
int rers_get_edge_count();
const char* rers_get_edge_name(int index);
int rers_get_edge_type(int edge);
void rers_get_initial_state(int *t);
int rers_get_successor_all (void* model, int *in, TransitionCB callback, void *arg);
int rers_get_successor (void* model, int t, int *in, TransitionCB callback, void *arg);
int rers_get_actions (void* model, int t, int *i, TransitionCB callback, void *arg);
const char* rers_get_type_value_name(int type, int value);
int rers_get_label_count();
int rers_get_guard_count();
void rers_get_labels_all(void* model, int* i, int* label);
int rers_get_label(void* model, int g, int* in);
int rers_get_transition_groups();
const int* rers_get_transition_read_dependencies(int t);
const int* rers_get_actions_read_dependencies(int t);
const int* rers_get_transition_may_write_dependencies(int t);
const int* rers_get_transition_must_write_dependencies(int t);
const int* rers_get_label_matrix(int g);
const int*** rers_get_all_labels();
void rers_get_labels_many (void* model, int* in, int* label, int guards_only);
const char *rers_get_label_name(int g);